 
name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        configuration_path: .github/workflows/greetings/greetings.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you! Your issue will be reviewed!'
        pr-message: 'Congrats on your first PR!'