version: '3'
services:
  bot:
    build: .
    container_name: 'talosbot'
    environment:
      TALOS_TOKEN: ${TALOS_TOKEN}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    restart: always
    volumes:
      - .:/talosbot
    working_dir: /talosbot
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local