version: '3'

services:
  bot:
    build: .
    container_name: 'talosbot'
    environment:
      TALOS_TOKEN: ${TALOS_TOKEN}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    restart: always
    volumes:
      - ./ai_bot:/ai_bot
    working_dir: /ai_bot
    command: python -u bot.py