version: '3'

services:
  bot:
    build: .
    container_name: 'talosbot'
    environment:
      TALOS_TOKEN: ${TALOS_TOKEN}
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
    restart: always
    volumes:
      - .:/talos
    working_dir: /talos
    command: bash -c "pip install . && talos"