version: '3'
services:
  bot:
    build: .
    container_name: 'talosbot'
    restart: always
    volumes:
      - ./talos:/talos/talosbot
    working_dir: /talos
    command: poetry run talosbot run
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - db-data:/data/db
volumes:
  db-data:
    driver: local