name: "PR Labeler"
on:
  pull_request:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}