name: talos-deploy
on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Amazon EC2 tests
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Talos
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOST }}" > ~/.ssh/known_hosts
        eval `ssh-agent`
        ssh-add - <<< "${{ secrets.EC2_KEY }}"
        ssh ubuntu@ec2-3-8-149-83.eu-west-2.compute.amazonaws.com 'sudo rm -rf Talos && git clone https://github.com/npitsillos/Talos && cd Talos && touch .env && echo "${{ secrets.TALOS_TOKEN }}" >> .env && echo "${{ secrets.KAGGLE_USERNAME }}" >> .env && echo "${{ secrets.KAGGLE_KEY }}" >> .env && docker-compose -f docker-commpose.yml -f docker-compose.prod.yml up'
