name: talos-deploy
on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest

    steps:
    - name: Setup SHH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" > talos-key.pem
        chmod 400 talos-key.pem

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Deploy Talos
      run: |
        ssh -t ubuntu@ec2-3-8-149-83.eu-west-2.compute.amazonaws.com "mkdir test"