name: talos-deploy
on:
  push:
    branches: [main, talos-dev]
  pull_request:
    branches: [talos-dev]

jobs:
  deploy:
    name: Deploy to Amazon EC2
    runs-on: ubuntu-latest
    env:
      TALOSBOT_DB_URL: mongodb://mongo/talosbot
      TALOSBOT_GIT_REPO: https://github.com/npitsillos/talos.git
      TALOSBOT_ADMIN_ROLE: mastros
      TALOSBOT_COMMAND_PREFIX: '!'
      TALOSBOT_DISCORD_BOT_TOKEN: "${{ secrets.DISCORD_BOT_TOKEN }}"

    steps:
    - uses: actions/checkout@v2
      with:
        ref: $GITHUB_REF_NAME
    - name: Deploy Talos
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.HOST }}" > ~/.ssh/known_hosts
        eval `ssh-agent`
        ssh-add - <<< "${{ secrets.EC2_KEY }}"
        env | grep TALOSBOT > .env
        echo KAGGLE_USERNAME="${{ secrets.USERNAME }}" >> .env && echo KAGGLE_KEY="${{ secrets.KAGGLE_KEY }}" >> .env
        ssh ubuntu@ec2-3-8-59-142.eu-west-2.compute.amazonaws.com 'sudo rm -rf talos && git clone https://github.com/npitsillos/talos'
        scp .env ubuntu@ec2-3-8-59-142.eu-west-2.compute.amazonaws.com:/home/ubuntu/talos/.env
        ssh ubuntu@ec2-3-8-59-142.eu-west-2.compute.amazonaws.com 'cd talos && docker-compose -f docker-compose.yml up --build -d'